#!/usr/bin/env bash

# load scripting additions
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config window_placement second_child
# desktop
# yabai -m config top_padding 40
# yabai -m config bottom_padding 40
# yabai -m config left_padding 40
# yabai -m config right_padding 40
# yabai -m config window_gap 20
# laptop
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 6
yabai -m config window_shadow float
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.15
yabai -m config active_window_opacity 1.0
yabai -m config external_bar all:32:0
yabai -m config split_ratio 0.50
yabai -m config mouse_follows_focus off

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize
# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m config mouse_drop_action swap

#
# setup spaces
#
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 5)'); do
	yabai -m space --destroy 6
done

function setup_space {
	local idx="$1"
	local name="$2"
	local space=
	echo "setup space $idx : $name"

	space=$(yabai -m query --spaces --space "$idx")
	if [ -z "$space" ]; then
		yabai -m space --create
	fi

	yabai -m space "$idx" --label "$name"
}
setup_space 1 code
setup_space 2 web
setup_space 3 social
setup_space 4 other
setup_space 5 media

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Numi$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Fig$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Microsoft Teams (work or school)$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off

echo "yabai configuration loaded..."
